//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestorRecursosHumanos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SGRHEntities : DbContext
    {
        public SGRHEntities()
            : base("name=SGRHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cargos> cargos { get; set; }
        public virtual DbSet<departamentos> departamentos { get; set; }
        public virtual DbSet<empleados> empleados { get; set; }
        public virtual DbSet<entradaEmpleados> entradaEmpleados { get; set; }
        public virtual DbSet<licencias> licencias { get; set; }
        public virtual DbSet<nomina> nomina { get; set; }
        public virtual DbSet<permisos> permisos { get; set; }
        public virtual DbSet<salidaEmpleado> salidaEmpleado { get; set; }
        public virtual DbSet<vacaciones> vacaciones { get; set; }
    }
}
