//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaGestorRecursosHumanos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SGRHEntities : DbContext
    {
        public SGRHEntities()
            : base("name=SGRHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cargos> cargos { get; set; }
        public virtual DbSet<departamentos> departamentos { get; set; }
        public virtual DbSet<empleados> empleados { get; set; }
        public virtual DbSet<entradaEmpleados> entradaEmpleados { get; set; }
        public virtual DbSet<licencias> licencias { get; set; }
        public virtual DbSet<nomina> nomina { get; set; }
        public virtual DbSet<permisos> permisos { get; set; }
        public virtual DbSet<salidaEmpleado> salidaEmpleado { get; set; }
        public virtual DbSet<vacaciones> vacaciones { get; set; }
    }
}
